[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://*.thinkific.com https://thinkific.com https://learn.thinkific.com"

[[headers]]
  for = "/config.js"
  [headers.values]
    content-type = "application/javascript"
    cache-control = "no-cache"

[[headers]]
  for = "/dist/*"
  [headers.values]
    content-type = "text/css"
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript" 