[build]
  publish = "."
  command = ""

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/config.js"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 